Fix LLVM module dump linker error (#1483)
Replaces instances of `llvm::Module::dump()` with
`llvm::Module::print()` with the `llvm::errs()` output stream as an
argument. This is essentially what dump() does under the hood anyway,
and does not lead to any change in behavior.

This fixes an error where the project wouldn't compile due to the linker
not finding the `dump()` method, as it is not included by default in
LLVM. Below is the output of the error on Apple clang v17.0.0.

```bash
Undefined symbols for architecture arm64:
  "llvm::Module::dump() const", referenced from:
      IpGraphToLlvmConverterTests_LoadConversion_Test::TestBody() in IpGraphToLlvmConverterTests.la
      IpGraphToLlvmConverterTests_LoadVolatileConversion_Test::TestBody() in IpGraphToLlvmConverterTests.la
      IpGraphToLlvmConverterTests_MemCpyConversion_Test::TestBody() in IpGraphToLlvmConverterTests.la
      IpGraphToLlvmConverterTests_MemCpyVolatileConversion_Test::TestBody() in IpGraphToLlvmConverterTests.la
      IpGraphToLlvmConverterTests_StoreConversion_Test::TestBody() in IpGraphToLlvmConverterTests.la
      IpGraphToLlvmConverterTests_StoreVolatileConversion_Test::TestBody() in IpGraphToLlvmConverterTests.la
      IpGraphToLlvmConverterTests_FMulAddConversion_Test::TestBody() in IpGraphToLlvmConverterTests.la
      ...
ld: symbol(s) not found for architecture arm64
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

Co-authored-by: Nico Reissmann <nico.reissmann@gmail.com>