Avoid g++ 13.3.0 compiler errors in release build (#1576)
When we build jlm in release with g++ 13.3.0 we get the following errors
due to -Werror:

```
/usr/include/c++/13/bits/stl_algobase.h:437:30: error: ‘void* __builtin_memmove(void*, const void*, long unsigned int)’ forming offset 8 is out of the bounds [0, 8] [-Werror=array-bounds=]
  437 |             __builtin_memmove(__result, __first, sizeof(_Tp) * _Num);


 /usr/include/c++/13/bits/stl_algobase.h:437:30: error: ‘void* __builtin_memmove(void*, const void*, long unsigned int)’ writing between 9 and 9223372036854775807 bytes into a region of size 8 overflows the destination [-Werror=stringop-overflow=]
  437 |             __builtin_memmove(__result, __first, sizeof(_Tp) * _Num);
```

Those are false positive warnings that are converted to errors with
`-Werror`. This PR changes the code slightly to avoid these warnings and
therefore the errors.