Changes needed to compile on macOS (#761)
Currently, tests/jlm/util/TestBijectiveMap.cpp causes a compilation
error on macOS

In file included from tests/jlm/util/TestBijectiveMap.cpp:9:
In file included from ./jlm/util/BijectiveMap.hpp:11:

/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/unordered_map:680:17:
fatal error: no viable overloaded '='
        __ref() = __v.__get_value();
        ~~~~~~~ ^ ~~~~~~~~~~~~~~~~~

/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__hash_table:1779:47:
note: in instantiation of member
function 'std::__1::__hash_value_type<int, const
std::__1::basic_string<char> >::operator=' requested here
                __cache->__upcast()->__value_ = *__first;

---------

Co-authored-by: Nico Reissmann <nico.reissmann@gmail.com>
Co-authored-by: caleridas <36173465+caleridas@users.noreply.github.com>